dist: trusty

language: java

jdk:
  - oraclejdk11

os:
  - linux

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle

jobs:
  include:
    - stage: clean and build
      script:
        - ./gradlew clean build
    - stage: build and push docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build -t ci-learn .
        - docker images
        - docker tag ci-learn $DOCKER_USERNAME/ci-learn
        - docker push $DOCKER_USERNAME/ci-learn
