dist: trusty

language: java

jdk:
  - oraclejdk11

os:
  - linux

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew clean install
